version: '3'
services:
  demo-mongo-2:
    image: mongo
    networks:
      - develop-network

  microservice:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: silasca/music-library-reactive-api
    container_name: music-library-reactive-api
    ports:
      - 8080:8080
    networks:
      - develop-network
    depends_on:
      - "demo-mongo-2"

networks:
  develop-network:
    driver: bridge